const express=require('express')
const cors = require('cors')
const{app,server}=require('./socket')
const{notificationRouter}=require('./Routes/notification_routes')
const{userRouter}=require('./Routes/user_routes')
const{courseRouter}=require('./Routes/course_routes')
const{messageRouter}=require('./Routes/message_routes')
const{jobRouter}=require("./Routes/job_routes")
app.use(cors())
app.use(express.json())
app.use("/maritimenotifications",notificationRouter)
app.use("/maritime/user",userRouter)
app.use("/maritime/course",courseRouter)
app.use("/maritime/job",jobRouter)
app.use("/maritime/message",messageRouter)
const PORT=process.env.PORT||5005
server.listen(PORT,()=>{
    console.log(PORT)
})